name:  sockjs_client
version: 0.2.0
description:  A SockJS client in Dart
homepage: https://github.com/nelsonsilva/sockjs-dart-client
authors:
- Nelson Silva <nelson.silva@inevo.pt>
- Sébastien Deleuze
dependencies:
  browser: 
    git:
      url: 'https://github.com/cicadabear/browser.git'
  logging: '>=0.9.0 <1.0.0'
environment:
  sdk: '>=1.0.0 <3.0.0'
